### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by sebleier** [valueof/hiro#1]
Hi, 
This looks like a nice testing framework, but it doesn't have a license file or any license embedded in the source code.  Would you mind adding one? _cough_ Permissive license _cough_

Thanks

**Comment by valueof** [comment]
Added MIT License comment block in 9ddbb11e14aa3d94e83affa21e0586fd63ae6415. Thanks!

**Comment by sebleier** [comment]
Awesome, thanks :)
