### ISSUE TITLE
Extra assertions

### ISSUE THREAD

**Issue by marijn** [valueof/hiro#10]
I think it would be nice to have a few more assertions. 
- `assertGreaterThan`
- `assertGreaterThanOrEqualTo`
- `assertLessThan`
- `assertLessThanOrEqualTo`
- `assertUndefined`
- `assertNull`
- `assertInstanceOf`
- `assertObjectHasProperty`
- `assertArrayContains`

I'm not to sure about the names of the last two. What do you think? 

Would you like me to open a PR?

**Comment by valueof** [comment]
`assertGreaterThan(x, y)` is actually longer than `assertTrue(x > y)`.

But the last four are good.

**Comment by marijn** [comment]
The point of `assertGreaterThan` and friends is to add some semantics on what is being tested and expected.

**Comment by valueof** [comment]
I see the point with semantics. I'll sleep on the idea.

**Comment by marijn** [comment]
I've worked on a basic implementation. Would you mind if I also refactored the tests of the assertions a bit?

**Comment by valueof** [comment]
Nope, go for it.

**Comment by valueof** [comment]
Both patches had been resolved in `hiro2` branch.
