### ISSUE TITLE
Strict comparison in assert methods

### ISSUE THREAD

**Issue by marijn** [valueof/hiro#13]
Right now the assert functions are using loose comparison operators within the assert methods, is there any particular reason not to use strict comparisons?

**Comment by valueof** [comment]
We used to use loose comparisons quite a lot in our project when I extracted Hiro out of it but I just didn't feel like updating the library (if it works, don't touch it). :-)

**Comment by valueof** [comment]
Hiro 2 (see the branch) now uses Underscore's strict/deep equal implementation `_.isEqual`.
